services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    # ports:
    #   - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    # ports:
    #   - "3306:3306" # Open for debugging, TODO: remove
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasktrack
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf


volumes:
  mysql_data: