services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "80:80" # http, TODO: https
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # Open for debugging, TODO: remove
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasktrack
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: