/**
 * TaskTrack
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DateData { 
    year?: number;
    month?: number;
    day?: number;
}

export function DateData(year: number, month: number, day: number): DateData {
    return {
        year: year,
        month: month,
        day: day
    }
}

export function DateDataFromDate(date: Date): DateData {
    return {
        year: date.getFullYear(),
        month: date.getMonth(),
        day: date.getDate()
    }
}

export function toDateString(date: DateData): string {
    if (!date.year || !date.month || !date.day) {
        throw new Error("DateData object is missing year, month, or day.");
    }
    return `${date.year}-${String(date.month).padStart(2, '0')}-${String(date.day).padStart(2, '0')}`;
}