/**
 * TaskTrack
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DateData } from './dateData';
import { EventEntry } from './eventEntry';
import { PriorityLevel } from './priorityLevel';

export interface EventData { 
    title?: string;
    description?: string;
    dueDate?: DateData;
    priority?: PriorityLevel;
}