/**
 * TaskTrack
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PriorityLevel = 0 | 1 | 2;

export const PriorityLevel = {
    NUMBER_0: 0 as PriorityLevel,
    NUMBER_1: 1 as PriorityLevel,
    NUMBER_2: 2 as PriorityLevel
};