/**
 * TaskTrack
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { EventData } from '../model/eventData';
import { EventEntry } from '../model/eventEntry';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EventService {

    protected basePath = 'http://api.localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eventsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<EventEntry>>;
    public eventsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EventEntry>>>;
    public eventsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EventEntry>>>;
    public eventsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        const token = localStorage.getItem('jwtToken');
        if (token) {
            headers = headers.set('Authorization', `Bearer ${token}`);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<EventEntry>>('get',`${this.basePath}/events`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eventsIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<EventEntry>;
    public eventsIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventEntry>>;
    public eventsIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventEntry>>;
    public eventsIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling eventsIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        const token = localStorage.getItem('jwtToken');
        if (token) {
            headers = headers.set('Authorization', `Bearer ${token}`);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EventEntry>('delete',`${this.basePath}/events/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eventsIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<EventEntry>;
    public eventsIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventEntry>>;
    public eventsIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventEntry>>;
    public eventsIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling eventsIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        const token = localStorage.getItem('jwtToken');
        if (token) {
            headers = headers.set('Authorization', `Bearer ${token}`);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EventEntry>('get',`${this.basePath}/events/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eventsIdPut(id: number, body?: EventData, observe?: 'body', reportProgress?: boolean): Observable<EventEntry>;
    public eventsIdPut(id: number, body?: EventData, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventEntry>>;
    public eventsIdPut(id: number, body?: EventData, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventEntry>>;
    public eventsIdPut(id: number, body?: EventData, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling eventsIdPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        const token = localStorage.getItem('jwtToken');
        if (token) {
            headers = headers.set('Authorization', `Bearer ${token}`);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<EventEntry>('put',`${this.basePath}/events/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param n 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eventsNextNGet(n: number, observe?: 'body', reportProgress?: boolean): Observable<Array<EventEntry>>;
    public eventsNextNGet(n: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EventEntry>>>;
    public eventsNextNGet(n: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EventEntry>>>;
    public eventsNextNGet(n: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (n === null || n === undefined) {
            throw new Error('Required parameter n was null or undefined when calling eventsNextNGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        const token = localStorage.getItem('jwtToken');
        if (token) {
            headers = headers.set('Authorization', `Bearer ${token}`);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<EventEntry>>('get',`${this.basePath}/events/next/${encodeURIComponent(String(n))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eventsPost(body?: EventData, observe?: 'body', reportProgress?: boolean): Observable<EventEntry>;
    public eventsPost(body?: EventData, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventEntry>>;
    public eventsPost(body?: EventData, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventEntry>>;
    public eventsPost(body?: EventData, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        const token = localStorage.getItem('jwtToken');
        if (token) {
            headers = headers.set('Authorization', `Bearer ${token}`);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<EventEntry>('post',`${this.basePath}/events`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
}
